#!/bin/bash

BASEDIR="/opt/teamspeak3-server"

export LD_LIBRARY_PATH="${BASEDIR}${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"

# work around tsdns always reading its config from the dir it's ran from
cd "/etc/teamspeak3-server"

exec "${BASEDIR}/bin/tsdnsserver" "$@"
