#!/sbin/runscript

depend() {
	need net
	before tvheadend
}

start() {
	ebegin "Starting oscam"

	mkdir -p /run/oscam/tmp
	chown -R "${OSCAM_USER}:${OSCAM_GROUP}" /run/oscam /var/log/oscam

	start-stop-daemon --start --user "${OSCAM_USER}:${OSCAM_GROUP}" --exec /usr/bin/oscam -- \
		-b -B /run/oscam/oscam.pid -c /etc/oscamconf -t /run/oscam/tmp ${OSCAM_OPTIONS}
	eend $?
}

stop() {
	ebegin "Stopping oscam"
	start-stop-daemon --stop --quiet --pidfile /run/oscam/oscam.pid
	eend $?
}

